name: Generate Snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.3.0
